# Deployment for backend API
apiVersion: v1
kind: Service
metadata:
  name: core-api
  labels:
    app: core-api
    tier: backend
    role: master
    version: 0.0.1
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
  selector:
    app: core-api
    tier: backend
    role: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: core-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: core-api
        tier: backend
        role: master
        version: 0.0.1
    spec:
      volumes:
        - name: configmap-volume
          configMap:
            name: nginx-api-configmap
      containers:
      - name: api
        image: gcr.io/store-name-generator/api:v1.1.0
        ports:
        - containerPort: 5000
      - name: webserver
        image: nginx
        volumeMounts:
        # TODO: SSL
        # - mountPath: /etc/nginx/ssl
        #   name: secret-volume
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
    tier: frontend
    role: master
    version: 0.0.1
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
  selector:
    app: web-app
    tier: frontend
    role: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app
        tier: frontend
        role: master
        version: 0.0.1
    spec:
      volumes:
        - name: static-volume
          emptyDir: {}
      containers:
      - name: web-app
        image: gcr.io/store-name-generator/web:v1.1.0
        volumeMounts:
        - mountPath: /static
          name: static-volume
      - name: webserver
        image: nginx
        volumeMounts:
        # TODO: SSL
        # - mountPath: /etc/nginx/ssl
        #   name: secret-volume
        - mountPath: /usr/share/nginx/html
          name: static-volume
        # - mountPath: /etc/nginx/conf.d
        #   name: configmap-volume
        ports:
        - containerPort: 80
